### ISSUE TITLE
Segmentation fault when trying to sideload

### ISSUE THREAD

**Issue by PinguThePenguin007** [Dadoum/Sideloader#1]
OS: Arch Linux with KDE Plasma 
Device: Iphone X with iOS 16.1.1
IPA: Sidestore 0.5.1 Nightly (2023/09/18)

After connecting my device and selecting the IPA to sideload, Sideloader produces this error and crashes, no matter what IPA i use:

```
$ ./sideloader-x86_64 
                    main INFO  2023-10-21T01:43:02.525 Sideloader, compiled with LDC on Oct 20 2023 at 19:49:59
                    main INFO  2023-10-21T01:43:02.525 Configuration path: /home/pingu/.config/Sideloader

(sideloader-x86_64:10471): Adwaita-WARNING **: 01:43:02.725: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
...eloadergtkapplication INFO  2023-10-21T01:43:02.936 Device <my-device's id> (usbmuxd) has been connected.
         ui.devicewidget INFO  2023-10-21T01:43:28.301 Application "/home/pingu/stuff/AltServer_stuff/ipas/SideStore-0.5.1-nightly.2023.09.18.144125a5.ipa" selected for installation.
Segmentation fault (core dumped)
```

Will provide more info as needed, because i'm not very experienced at reporting bugs. :)

By the way, while i'm here, i'd like to thank you for all of your hard work and dedication to this, it's amazing what you're doing! :D

**Comment by PinguThePenguin007** [comment]
Oh, i didn't notice you already fixed it while i was writing the issue, that's awkward :O

I'm very sorry...

**Comment by PinguThePenguin007** [comment]
The issue still seems to persist, though, so i'm going to reopen it. 

That is very awkward...

**Comment by Dadoum** [comment]
Okay I made a second attempt to fix that issue

**Comment by PinguThePenguin007** [comment]
That is fast :D 
Unfortunately, i won’t be able to check the fix out soon, but i’ll do as soon as i’ll get the chance!
