### ISSUE TITLE
Building requires a Github login and password now?

### ISSUE THREAD

**Issue by asdhio-github** [Dadoum/Sideloader#16]
When running `dub build`, it outputs the following:
```
Username for 'https://github.com': username
Password for `'https://username@github.com':
```
Earlier builds did not have this requirement. Why was it introduced?

**Comment by Dadoum** [comment]
If you build the main branch since my fork of botan does not exist anymore it will fail to fetch it. It asks for credentials as it thinks it may be private.

**Comment by Dadoum** [comment]
this already has been fixed
