### ISSUE TITLE
Error message in Arch linux

### ISSUE THREAD

**Issue by julilujuluilu** [Dadoum/Sideloader#19]
I installed all dependencies listed, only happens in arch, any way I can fix that?
$ 

```
./sideloader
object.Exception@/root/.dub/packages/requests/2.1.1/requests/source/requests/ssl_adapter.d(204): loading openssl: unknown version Tuple!(int, "major", int, "minor")(3, 2) for init
```

**Comment by Dadoum** [comment]
Use the latest GTK+ build from GitHub actions. Expect bugs though as I haven't got a lot of time to debug and fix bugs.

**Comment by julilujuluilu** [comment]
Thanks, that worked!

**Comment by TheCheddarCheese** [comment]
> Use the latest GTK+ build from GitHub actions. Expect bugs though as I haven't got a lot of time to debug and fix bugs.

dumb question but where do i download it

**Comment by Dadoum** [comment]
> > Use the latest GTK+ build from GitHub actions. Expect bugs though as I haven't got a lot of time to debug and fix bugs.
> 
> dumb question but where do i download it

https://github.com/Dadoum/Sideloader/actions/runs/8124788660#artifacts
