### ISSUE TITLE
Windows CLI builds from GitHub Actions are not working

### ISSUE THREAD

**Issue by mega6453** [Dadoum/Sideloader#22]
**app** means, is it expecting .app folder or .ipa file? In both cases getting error as below. Please help.

C:\Users\mc\Desktop\sideloader>sideloader-cli-windows-x86_64.exe install app WebDriverAgentRunner-Runner.app
Error: Unrecognized arguments: ["WebDriverAgentRunner-Runner.app"]

C:\Users\mc\Desktop\sideloader>sideloader-cli-windows-x86_64.exe install app wda.ipa
Error: Unrecognized arguments: ["wda.ipa"]

C:\Users\mc\Desktop\sideloader>sideloader-cli-windows-x86_64.exe sign -c dev.p12 -k privkey.pem -m dev.mobileprovision app WebDriverAgentRunner-Runner.app
Error: Unrecognized arguments: ["WebDriverAgentRunner-Runner.app"]

C:\Users\mc\Desktop\sideloader>sideloader-cli-windows-x86_64.exe sign -c dev.p12 -k privkey.pem -m dev.mobileprovision app wda.ipa
Error: Unrecognized arguments: ["wda.ipa"]

**Comment by Dadoum** [comment]
This is an issue I was not encountering on my computer, but then I just tried with the automated build and it just fails to run too. Something weird is happening ^^'

I can give you an executable that I built myself and works (at least in Wine, where I tested), but that's annoying, because like, I don't understand how the CI could produce executables which are not working.

**Comment by mega6453** [comment]
Ok, executable please...

**Comment by Dadoum** [comment]
[sideloader-build.zip](https://github.com/Dadoum/Sideloader/files/14472968/sideloader-build.zip)

**Comment by Dadoum** [comment]
Did it work eventually?

**Comment by P5-2005** [comment]
> Did it work eventually?

hi, thanks for this, i tried this build :
i get this :
```
C:\Users\PC\Downloads\Compressed\ProcessExplorer\sideloader-qt-windows>sideloader.exe app-id add -i
            cli_frontend INFO  2024-03-21T13:22:56.035 Logging in...
            cli_frontend INFO  2024-03-21T13:22:56.035 Please enter your account informations. They will only be sent to Apple servers.
            cli_frontend INFO  2024-03-21T13:22:56.035 See it for yourself at https://github.com/Dadoum/Sideloader/
Apple ID: REDACTED@gmail.com
1BC84DDC460 [/!\ The password will appear in clear text in the terminal]: REDACTED
 server.developersession INFO  2024-03-21T13:23:10.148 Creating DeveloperSession for REDACTED@gmail.com...
     server.appleaccount INFO  2024-03-21T13:23:10.148 Logging in...
A code has been sent to your devices, please type it here (type `resend` to resend one): 074397
 server.developersession ERROR 2024-03-21T13:23:28.843 DeveloperSession creation failed: This action cannot be completed at this time
            cli_frontend ERROR 2024-03-21T13:23:28.858 Can't log-in! This action cannot be completed at this time (-22411)
            ```

**Comment by Dadoum** [comment]
The first error is due to Apple not trusting Sideloader. But eventually after some time it let you use it.

And the second is my bad, to add an app id you need to specify a few fields and I didn't check them before. The actual syntax is 
```
$ ./sideloader-cli-linux-x86_64 app-id add -h
Usage: sideloader-cli-linux-x86_64 app-id add [-i] [--team TEAMID] [-h] name identifier

Add a new App ID.

Required arguments:
  name                 app name
  identifier           app identifier

Optional arguments:
  -i, --interactive    Prompt to type passwords if needed.
  --team TEAMID        Team ID
  -h, --help           Show this help message and exit
  -d, --debug          Enable debug logging
```

Otherwise, sorry for the late answer I have been more busy irl.

**Comment by Dadoum** [comment]
(resolved)
