### ISSUE TITLE
Sideloading error: Object is a 'plist.PlistData' and cannot be converted into the specified type

### ISSUE THREAD

**Issue by babaruh** [Dadoum/Sideloader#25]
I had to reinstall uYouPlus and usually everything worked but this time I got an error
`Sideloading error: Object is a 'plist.PlistData' and cannot be converted into the specified type`
## steps to reproduce.
1. download Sideloader https://github.com/Dadoum/Sideloader/actions/runs/8370462902
2. build your own uYouPlus.ipa
3. pair with iphone(ios 17.4.1)
4. choose ipa
5. get error

**Comment by Dadoum** [comment]
(should be fixed)
