### ISSUE TITLE
[Question]: How do I go about building an ipa on Linux with theos?

### ISSUE THREAD

**Issue by mak448a** [Dadoum/Sideloader#4]
Theos building was mentioned in the readme, could you help me a bit? Thank you.

**Comment by Dadoum** [comment]
You always had multiple way to compile iOS apps on Linux. With theos, you have to set-up an iOS application (in Swift or Objective-C) with nic.pl, then you add to your Makefile the `PACKAGE_FORMAT` line I given in the readme. Then when you'll run `make package`, this will build an unsigned ipa. 

That ipa, you can install it with sideloader onto your device. You could also download certificates with the upcoming sideloader cli, and sign it yourself and install it if it fits more with your workflow. Finally, you could debug it with `idevicedebug`, `idevicedebugserver` and `lldb`, even if I never tested that part tbh.

By the way, theos isn't your only option. If you prefer some other programming language like Rust or D, you can build the app bundle yourself, or if you want to use the Swift Package Manager, you can use this [awesome project](https://github.com/kabiroberai/linux-app/) that will allow you to make apps for iOS from Linux with SPM.

**Comment by mak448a** [comment]
I know this is a bit out of nowhere, but I just started to check this out. Do you know of any way this could be used to build an XCode project exported from Godot Engine? If not, are there any resources for learning SwiftUI with Theos?

**Comment by mak448a** [comment]
Do you know of any resources to get started with the project that nic.pl spits out? I successfully built an ipa from it. I just used "[3.] iphone/application".
