### ISSUE TITLE
Unable to install IPA (You already have a current iOS Development certificate or a pending certificate request.)

### ISSUE THREAD

**Issue by steilerDev** [Dadoum/Sideloader#41]
When trying to install an IPA (that I've previously successfully installed) I'm getting the following error:

```
server.developersession.ExceptionType(server.developersession.DeveloperPortalError).ExceptionType at source/server/{
        statusCode = 7460
        description = You already have a current iOS Development certificate or a pending certificate request.
}
```

Running on a Raspberry Pi 5 (latest commit) - `/opt/sideloader-cli install --udid <someUDID> "/opt/apps/SomeApp.ipa"`

**Comment by Dadoum** [comment]
You can manage your certificates with `/opt/sideloader-cli cert` to revoke any certificate you're not using. That's an Apple error saying that some app has already generated a developer certificate for your account.

**Comment by steilerDev** [comment]
That did the trick - thank you!

**Comment by Nolannn2222** [comment]
how to do that

**Comment by brunoaduarte** [comment]
> how to do that

```
./sideloader-cli-arm64-apple-macos cert list -i
./sideloader-cli-arm64-apple-macos cert revoke XXXXXXXXXXXXXX -i
```

**Comment by Dimmmo281** [comment]
tell me in more detail how to do this on Ubuntu, all profiles on Afion have been deleted, what needs to be done?

**Comment by truongvantuan** [comment]
> tell me in more detail how to do this on Ubuntu, all profiles on iphone
> 
> have been deleted, what needs to be done?

@Dimmmo281 get from Actions https://github.com/Dadoum/Sideloader/actions/workflows/build-cli.yml
