### ISSUE TITLE
You are not logged in. (use `sidestore login` to log-in, or add `-i` to make us ask you the account)

### ISSUE THREAD

**Issue by vk8a8** [Dadoum/Sideloader#45]
I get this error. However, sidestore is not a command. sorry for my repeated requests!

**Comment by vk8a8** [comment]
command
`[vk8a8@vk8a8-ideapad5 ~/Downloads]$ ./sideloader-cli-linux-x86_64 -i
Error: Unrecognized arguments: ["-i"]`

**Comment by Dadoum** [comment]
Here is the help message that indicates how the tool works:

```
[vk8a8@vk8a8-ideapad5 ~/Downloads]$ ./sideloader-cli-linux-x86_64 -h
Usage: sideloader [-d] [-h] <command> [<args>]

Available commands:
  app-id         Manage App IDs.
  cert           Manage certificates.
  install        Install an application on the device (renames the app, register
                 the identifier, sign and install automatically).
  sign           Sign an application bundle.
  team           Manage teams.
  tool           Run Sideloader's tools.
  version        Print the version.

Optional arguments:
  -d, --debug    Enable debug logging
  -h, --help     Show this help message and exit      
```

You need first to select a command, and then you can add `-h` to see how to use that specific command.

Example:

```
[vk8a8@vk8a8-ideapad5 ~/Downloads]$ ./sideloader-cli-linux-x86_64 install -h
```

**Comment by vk8a8** [comment]
thaknks for more info, but i get an error:
`Signing the application bundle |########################        | 77/100            cli_frontend ERROR 2024-04-29T10:45:15.607 object.Exception at std/file.d:4101: Failed to stat file '/tmp/Spotify-8.5.60_Spotilife-1.8-Revised v2.ipa/Payload/Spotify.app/PlugIns/NotificationContentExtension.appex/SC_Info/NotificationContentExtension.sinf'
Segmentation fault (core dumped)
`

**Comment by vk8a8** [comment]
will put that in seprate issue
