### ISSUE TITLE
Cannot make any more app ID, you have to wait to get new app id

### ISSUE THREAD

**Issue by vk8a8** [Dadoum/Sideloader#49]
Creating App IDs for the application |##############                  | 44/100            cli_frontend ERROR 2024-05-16T13:18:05.770 sideload.NoAppIdRemainingException at source/sideload/package.d:89: Cannot make any more app ID, you have to wait until 2024-May-23 19:29:28 to get a new app ID

**Comment by Dadoum** [comment]
I can't do anything about it, it's Apple which sets the limit to 10 app ids per week

**Comment by vk8a8** [comment]
oh
i was trying over and over again to install because it worked if i did that before (segmentation faults)
i guess i did it too many times

**Comment by Dadoum** [comment]
If it's the same app it won't register a new app if each time. Only once.

**Comment by vk8a8** [comment]
strange... it was the same app

**Comment by Dadoum** [comment]
Check in the GTK front end what are those app ids. In the hamburger menu in the top left there is a menu for that. And the CLI can also list app ids

**Comment by vk8a8** [comment]
![image](https://github.com/Dadoum/Sideloader/assets/154634737/4229a198-7d5d-41a1-a9fd-416af22cf1da)
this kind of thing

**Comment by Dadoum** [comment]
Open Spotify ipa as a zip and remove everything related to notifications in the PlugIns folder. If it still doesn't work try to remove some others which don't look important. It should work at some point.

**Comment by vk8a8** [comment]
wow! it is letting me install, but is still stuck on the "signing application bundle."' should i repeat like i did before, or do something else?

**Comment by Dadoum** [comment]
I think you can retry as much as you want.

**Comment by vk8a8** [comment]
Signing the application bundle |###########################     | 87/100sideloader-cli-linux-x86_64: xplist.c:365: node_to_xml: Assertion `(node->children->count % 2) == 0' failed.
Aborted (core dumped)

this error i've never seen, maybe because i removed those files?

**Comment by Dadoum** [comment]
Don't worry, it's unrelated. That's due to the fact libplist is not made to be executed concurrently but I did use it as such a few times and I haven't got time to fix that.

**Comment by vk8a8** [comment]
wow! thanks, you are so helpful! its installed!

**Comment by dungsaga** [comment]
Sometimes I got a similar error after authenticating with my Apple ID:
```
 server.developersession INFO  2026-03-01T13:10:51.653 DeveloperSession created successfully.
sideloader-gtk-x86_64-linux-gnu: xplist.c:365: node_to_xml: Assertion `(node->children->count % 2) == 0' failed.
Aborted (core dumped)
```

**Comment by Dadoum** [comment]
same thing as I said before
