### ISSUE TITLE
Feature Request: Provision Arbitrary UDID

### ISSUE THREAD

**Issue by thdaemon** [Dadoum/Sideloader#70]
Sideloader is a great tool that solves my need for deploying IPA files on Linux. However, I hope it can create a mobileprovision and sign it for any UDID I specify (not just the UDID of a connected device). To describe my request, I will use a quick and dirty hack I implemented. I modified [`usbmuxd`](https://github.com/libimobiledevice/usbmuxd/) to change the UDID of all connected devices to a specified value, as shown below:

```
--- a/src/preflight.c
+++ b/src/preflight.c
@@ -387,7 +387,7 @@ void preflight_worker_device_add(struct device_info* info)
 
        memcpy(infocopy, info, sizeof(struct device_info));
        if (info->serial) {
-               infocopy->serial = strdup(info->serial);
+               infocopy->serial = strdup("112233445566778899aabbccddeeffffffffffff");
        }
 
        THREAD_T th;
diff --git a/src/usb.c b/src/usb.c
index d0e9afc..02c2765 100644
--- a/src/usb.c
+++ b/src/usb.c
@@ -291,6 +291,7 @@ static void get_serial_callback(struct libusb_transfer *transfer)
        }
        usbdev->serial[di] = '\0';
 
+       strcpy(usbdev->serial, "112233445566778899aabbccddeeffffffffffff");
        usbmuxd_log(LL_INFO, "Got serial '%s' for device %d-%d", usbdev->serial, usbdev->bus, usbdev->address);
 
        libusb_free_transfer(transfer);
```

After building and starting my patched usbmuxd, I connect my iPhone to the PC, then launch Sideloader. At this point, the device UDID displayed in the GUI is the arbitrary UDID I set. I proceed with sideloading the IPA. While the installation obviously fails at the end, I do get a mobileprovision file with my custom UDID and a signed app bundle under /tmp/XXXX.ipa/ (which I can then install directly onto the desired device without needing Sideloader).

Perhaps adding this feature to the GUI is unnecessary, but it could be useful to have a CLI option for an "add device" feature? It seems that `DeveloperPortalResponse!DeveloperDevice addDevice` might be what I need, but I’m not familiar with the D language. Could you please consider my suggestion to make Sideloader more flexible (In other words, this essentially allows users to manually complete the process of "adding a device to their own Apple Developer ID", "obtaining the mobileprovision, certificate, and private key", and "signing the app bundle". Sideloader already does a great job with the latter two. If the first part can be achieved, signing could be done without connecting a device, and it would even eliminate the dependency on usbmuxd.)?

**Comment by Dadoum** [comment]
I am surprised I didn't implemented that earlier. I going to add a `device` subcommand to the cli.

**Comment by thdaemon** [comment]
Thank you for the quick response! I'm really excited to hear that you're planning to implement this feature. Looking forward to trying it out when it's ready!
