### ISSUE TITLE
How to download the windows cli tool?

### ISSUE THREAD

**Issue by mega6453** [Dadoum/Sideloader#9]
How to install says : 

_Currently, the only builds available can be downloaded through GitHub Actions.
On Windows, it will get a GitHub Release with a simple executable to run._

But I couldn't find a way to download... Any help please...

**Comment by Dadoum** [comment]
Here is a link for the new CLI I am working on [https://github.com/Dadoum/Sideloader/actions/runs/7212567270](https://github.com/Dadoum/Sideloader/actions/runs/7212567270)

Expect issues as it's has not been thoroughly tested, don't hesitate to post issues if you encounter any.

**Comment by Dadoum** [comment]
Now there is a release for it.
